### ISSUE TITLE
MacOS install - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by maoo** [WasmEdge/WasmEdge#2568] opened 2023-06-07 10:15 UTC
## Description

Following https://wasmedge.org/book/en/quick_start/install.html to install on MacOS, I ran `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash`

I managed to solve it by using the following steps I [found on SO](https://stackoverflow.com/a/70495761):

1. Open the folder /Applications/Python 3.x (x is the version you are running - use `python --version` to know which version is currently used).
2. Double click the Install Certificates.command. It will open a terminal and install the certificate.

Happy to submit a PR to add a note to the installation guide, if that's confirmed/reproducible.

### Current State

I get an error saying
```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
```

### Expected

WasmEdge installation completes successfully.

## Environment

- Hardware Architecture: x86\_64
- Operating system: MacOS Ventura 13.3.1 (22E261)
- Python: 3.11.3

## Steps to Reproduce

Simply run `curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | bash` on MacOS, with a freshly installed Python.

**Comment by hydai** [comment] 2023-06-07 10:44
This is a common issue if users do fresh Python installation on macOS. There are maybe a thousand StackOverflow issues related to this one. However, this is a little bit hard to reproduce on the CI environment, say the GitHub Action image: https://github.com/WasmEdge/WasmEdge/actions/runs/5068016567/jobs/9099775119#step:3:5

I am happy to have your PR, which adds some notes for the macOS users. Also, I am unsure which is the best way to fix this one because there are several ways to fix it on StackOverflow. Or is this fixed by a new Python version?

**Comment by hydai** [comment] 2023-06-07 10:50
Just found a document for this: https://trailofbits.github.io/algo/deploy-from-macos.html#option-1-install-using-the-homebrew-package-manager

It seems like the brew will take care of this.

**Comment by maoo** [comment] 2023-06-07 11:04
Thanks for the quick response @hydai !

I've submitted a PR on https://github.com/WasmEdge/WasmEdge/pull/2569 . 

Regardless the PR gets merged, feel free to close this issue.

**Closed** 2023-06-07 16:44 UTC
Labels: documentation, platform-macos, c-Installer
