### ISSUE TITLE
Support for host functions to directly access the host data of their own module instance.

### ISSUE THREAD

**Issue by L-jasmine** [WasmEdge/WasmEdge#2723] opened 2023-08-07 12:01 UTC
Although WasmEdge_ModuleInstanceGetHostData allows obtaining host data from within a module instance, the module instance in the parameters of the host function is not the one to which it belongs.

**Comment by apepkuss** [comment] 2023-08-07 12:23
@hydai @q82419  The issue blocks `code-flows` project to support for `http_req_wasi 0.10`. Please help fix the issue. Thanks a lot!

cc. @DarumaDocker

**Comment by hydai** [comment] 2024-06-04 19:48
@apepkuss Do we still need this?

**Comment by apepkuss** [comment] 2024-06-05 03:02
@L-jasmine Please check if the issue is still necessary. Thanks!

**Comment by hydai** [comment] 2024-09-25 22:19
No updates. Closing it. Please feel free to reopen it if this feature is still needed.

**Closed by hydai** 2024-09-25 22:19 UTC
Labels: enhancement
