### ISSUE TITLE
Fail to execute the wasm file ?

### ISSUE THREAD

**Issue by Zhangyx24** [WasmEdge/WasmEdge#1705] opened 2022-07-31 14:04 UTC
## Description
[test.zip](https://github.com/WasmEdge/WasmEdge/files/9229014/test.zip)

When executing the test.wasm which is uploaded as test.txt in test.zip, the wasmedge prints:
[2022-07-31 14:01:14.896] [error] instantiation failed: unknown import, Code: 0x62
[2022-07-31 14:01:14.896] [error]     When linking module: "wasi_unstable" , function name: "args_get"
[2022-07-31 14:01:14.896] [error]     At AST node: import description
[2022-07-31 14:01:14.896] [error]     At AST node: import section
[2022-07-31 14:01:14.896] [error]     At AST node: module

### Current State

In macOS and ubuntu, the wasmedge both prints :

[2022-07-31 14:01:14.896] [error] instantiation failed: unknown import, Code: 0x62
[2022-07-31 14:01:14.896] [error]     When linking module: "wasi_unstable" , function name: "args_get"
[2022-07-31 14:01:14.896] [error]     At AST node: import description
[2022-07-31 14:01:14.896] [error]     At AST node: import section
[2022-07-31 14:01:14.896] [error]     At AST node: module

### Expected
Execute the go database in wasm file, and prints 
TiDB [pingcap]>

## Environment

- Hardware Architecture: (x86\_64 )
- Operating system: (e.g. Ubuntu 20.04 and macOS)

## Steps to Reproduce
`wasmedge test.wasm`

**Comment by hydai** [comment] 2022-08-01 01:50
The `wasi_unstable` is called `old/snapshot_0` now, which is deprecated and replaced with `wasi_snapshot_preview1`.

Unfortunately, we don't have a plan to implement it in the near future.

Duplicate of #1325

**Closed by hydai** 2022-08-01 01:50 UTC

**Comment by Zhangyx24** [comment] 2022-08-01 01:55
Ok, Thanks for your answer !
