### ISSUE TITLE
exec container process `/add.wasm`: Exec format error error while running runtime: exit status 1

### ISSUE THREAD

**Issue by JcJinChen** [WasmEdge/WasmEdge#1646] opened 2022-07-13 06:49 UTC
## Description
I want to create and run the container image for test. I referred to this article(https://wasmedge.org/book/en/kubernetes/demo/wasi.html).
I have followed the mentioned steps to build and install buildah.
At the same time, I builded image using the tool buildah.
```
$ sudo buildah images
REPOSITORY                    TAG      IMAGE ID       CREATED       SIZE
localhost/wasm-wasi-example   latest   d230f65c92e0   4 hours ago   2.01 MB
```

After, i creates a new working container using the command
```sudo buidah from localhost/wasm-wasi-example:latest```

```
sudo buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
67ac345ac1a7     *     d230f65c92e0 localhost/wasm-wasi-example:l... wasm-wasi-example-working-container
```
Everything is normal up to here, as expected.

However, i want to run a command inside of the container, the following error occurs,
```exec container process `/add.wasm`: Exec format error
error while running runtime: exit status 1.```
One more question, If I want to`crun` to manage a container, how will i do?
I find that it is wrong to use `crun` to run a container that is created by `buildah`.

### Current State
I cannot manage a container using `crun` or `buildah`

### Expected
Input:
```sudo buildah run wasm-wasi-example-working-container /add.wasm 2 2```
Output:
```4```

## Environment
x86
Ubuntu20.04

- Hardware Architecture: (e.g. x86\_64 or aarch64)
- Operating system: (e.g. Ubuntu 20.04 or CentOS 7.6)

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version:
- CMake version:
- CMake flags: (e.g. `-DCMAKE_BUILD_TYPE=Release -DWASMEDGE_BUILD_AOT_RUNTIME=ON`)
- Boost version:

## Steps to Reproduce
wasm app
https://github.com/second-state/wasm-learning/tree/master/cli/add
build image
https://wasmedge.org/book/en/kubernetes/demo/wasi.html

**Comment by hydai** [comment] 2022-07-13 06:56
Could you also provide your commands and dockerfile here?

**Comment by JcJinChen** [comment] 2022-07-13 07:01
the Dockerfile located in ~/wasm-learning/cli/add/target/wasm32-wasi/debug, context:
```
FROM scratch
ADD add.wasm /
CMD ["/add.wasm"]
```
which commands do you mean?

**Comment by hydai** [comment] 2022-07-13 07:03
Including how you create the docker image from the dockerfile, and change the execution mode of the wasm file, etc.

**Comment by JcJinChen** [comment] 2022-07-13 07:29
create the docker image:
```
sudo buildah build --annotation "module.wasm.image/variant=compat" -t wasm-wasi-example .
```

download wasm code
```
git clone https://github.com/second-state/wasm-learning
cd wasm-learning/cli/add
```
build wasm bytecode
```
rustup target add wasm32-wasi
cargo build --target wasm32-wasi --release
```
After above commands,I find the add.wasm in the path */debug/ not */release, maybe i forget to add the flag "--release", however,i think it's keypoint to cause this error.
Of course, I change the mode of the wasm file,
```
chmod +x ~/wasm-learning/cli/add/target/wasm32-wasi/debug/add.wasm
```

**Comment by hydai** [comment] 2022-07-13 07:45
Thanks, I am working on this.

**Comment by JcJinChen** [comment] 2022-07-13 07:50
> Thanks, I am working on this.
Well, I also find an acticle about [how to run OCI wasm compat images with buildah and podman](https://github.com/containers/crun/blob/main/docs/wasm-wasi-example.md), maybe i can try it first.

**Comment by hydai** [comment] 2022-08-30 08:38
I cannot reproduce this. And I already created several new docker images on `wasmedge/example-wasi` and `wasmedge/example-wasi-http`. So I am closing this. If you have any new updates, please feel free to open them again.

**Closed by hydai** 2022-08-30 08:38 UTC

**Comment by jcuffe** [comment] 2022-09-12 10:14
Experiencing this same issue. 

Reproduction:
1. Follow all steps, exactly, to install buildah and create image here: https://github.com/second-state/wasmedge-containers-examples/blob/main/http_server_wasi_app.md
2. Modify the `container_http_server.json` file found on this page: https://wasmedge.org/book/en/kubernetes/cri/crio.html#run-a-http-server-app
3. Create a pod and container:
```
sudo crictl runp sandbox_config.json
sudo crictl create $POD_ID container_http_server.json sandbox_config.json
```
4. Start the container:
```
sudo crictl start $CONTAINER_ID
```
5. Check the container logs:
```
sudo crictl logs $CONTAINER_ID
```
6. Observe error:
```
exec container process `/http_server.wasm`: Exec format error
```

Dockerfile:
```
FROM scratch
ADD http_server.wasm /
CMD ["/http_server.wasm"]
```

container_http_server.json:
```
{
  "metadata": {
    "name": "http_server"
  },
  "image": {
    "image": "localhost/http_server:latest"
  },
  "working_dir": "/",
  "envs": [],
  "tier": "backend",
  "log_path": "",
  "stdin": false,
  "stdin_once": false,
  "tty": false
}
```

sandbox_config.json:
```
{
  "metadata": {
    "name": "podsandbox12",
    "namespace": "default"
  },
  "dns_config": {
    "searches": [
      "8.8.8.8"
    ]
  }
}
```

**Comment by hydai** [comment] 2022-09-12 10:19
Hi @jcuffe 
Could you please provide the version of `crictl`, `crun`, and `wasmedge`?
Also, please provide the log from `crtctl info`.

**Comment by jcuffe** [comment] 2022-09-12 10:29
Thanks for the quick response @hydai!

I recently reinstalled wasmedge, so I recompiled crun to see if that could have caused the issue. I have not yet recompiled cri-o

```
$ crun -V
crun version 1.6.0.0.0.7-5159
commit: 21b47f0bb6abdc8a2caf505e7ab79101a2189021
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +WASM:wasmedge +YAJL

$ wasmedge --version
wasmedge version 0.11.0

$ crictl --version
crictl version v1.21.0

$ sudo crictl info
{
  "status": {
    "conditions": [
      {
        "type": "RuntimeReady",
        "status": true,
        "reason": "",
        "message": ""
      },
      {
        "type": "NetworkReady",
        "status": true,
        "reason": "",
        "message": ""
      }
    ]
  }
}
```

**Comment by hydai** [comment] 2022-09-12 10:39
Thanks for the information.
I would like to know the steps you used to produce the `localhost/http_server:latest` image.

Since like the version should be fine. 
You can check the version details here: https://github.com/second-state/wasmedge-containers-examples/runs/8303277709?check_suite_focus=true#step:7:6

**Comment by jcuffe** [comment] 2022-09-12 10:46
Buildah commands I've tried:
```
sudo buildah build --annotation "module.wasm.image/variant=compat" -t http_server .
sudo buildah build --annotation "module.wasm.image/variant=smart-compat" -t http_server .
sudo buildah build --annotation ["module.wasm.image/variant=compat"] -t http_server .
```

**Comment by hydai** [comment] 2022-09-12 10:52
Just want to double-check that everything is the same:

```
# Build http_server.wasm
cargo build --target wasm32-wasi --release
# Apply the executable properties
chmod +x http_server.wasm
# Create the container image
sudo buildah build --annotation "module.wasm.image/variant=compat-smart" -t http_server .
# Publish to docker hub
sudo buildah push --authfile ~/path/to/authfil http_server docker://docker.io/.../http_server:latest
```

**Comment by jcuffe** [comment] 2022-09-12 11:00
Yes, that is all correct. The only step I have invented myself was to change the `container_http_server.json` contents from the quick start, as the "from-scratch" Dockerfile seems to expect no arguments or commands.

**Comment by hydai** [comment] 2022-09-12 11:02
The `args` part should be kept.
https://github.com/second-state/wasmedge-containers-examples/blob/main/crio/http_server/container_http_server.json#L8-L10

**Comment by jcuffe** [comment] 2022-09-12 11:10
It works! Thank you for your patience! My fault was in assuming that the `args` and `annotations` properties of the JSON file were no longer needed if they were "baked in" to the image.

I have exhausted my curiosity for the day, but I am very excited to move forward and build an image for React streaming SSR.

Thank you again for your time.

**Comment by hydai** [comment] 2022-09-12 11:12
Awesome! Thanks for your update.
