### ISSUE TITLE
Go with tinygo: wasm function not found

### ISSUE THREAD

**Issue by NuSkooler** [WasmEdge/WasmEdge#2137] opened 2022-11-30 19:50 UTC
## Description
I'm attempting to follow the guide here: https://wasmedge.org/book/en/write_wasm/go.html to create a .wasm I can then execute with WasmEdge. When I run with `wasmedge` it cannot find the function, that from my understanding should be exported.

### Current State
```powershell
> cat .\src\fib.go
package main

func main() {
}

func fibArray(n int32) int32{
  arr := make([]int32, n)
  for i := int32(0); i < n; i++ {
    switch {
    case i < 2:
      arr[i] = i
    default:
      arr[i] = arr[i-1] + arr[i-2]
    }
  }
  return arr[n-1]
}
> tinygo build -target=wasi -o .\fib.wasm .\src\fib.go
> wasmedge --reactor .\fib.wasm fibArray 10
[2022-11-30 12:47:51.536] [error] wasmedge runtime failed: wasm function not found, Code: 0x05
[2022-11-30 12:47:51.537] [error]     When executing function name: "fibArray"
```

### Expected

`fib.wasm` should run and produce a result based on input.

## Environment
- Hardware Architecture: x86_64
- Operating system: Windows (Version 10.0.19044.2251)
- tinygo version 0.26.0 windows/amd64 (using go version go1.19.2 and LLVM version 14.0.0)

**Comment by hydai** [comment] 2022-11-30 19:57
Hi @NuSkooler 

The export statement is missing. You may need to declare your exported function with an extra comment:

```go
//export fibArray
func fibArray(n int32) int32{}
```

Ref: https://stackoverflow.com/questions/67978442/go-wasm-export-functions

**Comment by NuSkooler** [comment] 2022-11-30 19:58
@hydai Thank you so much for the super quick response -- I completely missed that the comment was functional. Works as expected now!

**Comment by hydai** [comment] 2022-11-30 20:00
Happy to hear that. Since the issue is resolved, I'm going to close this. Please create a new one if you have any other issues.

**Closed by hydai** 2022-11-30 20:00 UTC
