### ISSUE TITLE
Failed to build on Mac OS with M1 chip

### ISSUE THREAD

**Issue by wenym1** [WasmEdge/WasmEdge#1485] opened 2022-05-23 16:07 UTC
## Description

I was following the [Mac OS build guild](https://wasmedge.org/book/en/extend/build_on_mac.html) to build on my Macbook Pro with M1 chip, and the compilation failed. 

### Current State

Compilation failed with the following messages logged out.
```
FAILED: lib/host/wasi/CMakeFiles/wasmedgeHostModuleWasi.dir/macos.mm.o 
/opt/homebrew/opt/llvm@12/bin/clang++ -DSPDLOG_COMPILED_LIB -I/Users/williamwen/repo/temp/WasmEdge/thirdparty -I/Users/williamwen/repo/temp/WasmEdge/build/lib/system -I/Users/williamwen/repo/temp/WasmEdge/build/include -I/Users/williamwen/repo/temp/WasmEdge/include -I/Users/williamwen/repo/temp/WasmEdge/build/_deps/spdlog-src/include -isystem /opt/homebrew/include -O2 -g -DNDEBUG -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Werror -Wno-error=pedantic -Wno-psabi -Wno-c++20-designator -Wno-c99-extensions -Wno-covered-switch-default -Wno-documentation-unknown-command -Wno-error=nested-anon-types -Wno-error=old-style-cast -Wno-error=unused-command-line-argument -Wno-ctad-maybe-unsupported -Wno-gnu-anonymous-struct -Wno-keyword-macro -Wno-language-extension-token -Wno-newline-eof -Wno-shadow-field-in-constructor -Wno-signed-enum-bitfield -Wno-switch-enum -Wno-undefined-func-template -Wno-error=return-std-move-in-c++11 -std=c++17 -MD -MT lib/host/wasi/CMakeFiles/wasmedgeHostModuleWasi.dir/macos.mm.o -MF lib/host/wasi/CMakeFiles/wasmedgeHostModuleWasi.dir/macos.mm.o.d -o lib/host/wasi/CMakeFiles/wasmedgeHostModuleWasi.dir/macos.mm.o -c /Users/williamwen/repo/temp/WasmEdge/lib/host/wasi/macos.mm
In file included from /Users/williamwen/repo/temp/WasmEdge/lib/host/wasi/macos.mm:5:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:143: error: function does not return NSString
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
                                                         ~~~~~~~~~~~~~~                                                                       ^                  ~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:103:48: note: expanded from macro 'NS_FORMAT_ARGUMENT'
        #define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))
                                                      ^          ~
1 error generated.
```

In the ninja build file generated by cmake, the build command corresponding to the failed file `macos.mm` is
```
build lib/host/wasi/CMakeFiles/wasmedgeHostModuleWasi.dir/macos.mm.o: CXX_COMPILER__wasmedgeHostModuleWasi_RelWithDebInfo /Users/williamwen/repo/temp/WasmEdge/lib/host/wasi/macos.mm || cmake_object_order_depends_target_wasmedgeHostModuleWasi
  DEFINES = -DSPDLOG_COMPILED_LIB
  DEP_FILE = lib/host/wasi/CMakeFiles/wasmedgeHostModuleWasi.dir/macos.mm.o.d
  FLAGS = -O2 -g -DNDEBUG -flto=thin -arch arm64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk -fPIC -fvisibility=hidden -fvisibility-inlines-hidden -Wall -Wextra -Werror -Wno-error=pedantic -Wno-psabi -Wno-c++20-designator -Wno-c99-extensions -Wno-covered-switch-default -Wno-documentation-unknown-command -Wno-error=nested-anon-types -Wno-error=old-style-cast -Wno-error=unused-command-line-argument -Wno-ctad-maybe-unsupported -Wno-gnu-anonymous-struct -Wno-keyword-macro -Wno-language-extension-token -Wno-newline-eof -Wno-shadow-field-in-constructor -Wno-signed-enum-bitfield -Wno-switch-enum -Wno-undefined-func-template -Wno-error=return-std-move-in-c++11 -std=c++17
```

After I manually removed the `-isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk` option, the compilation succeeded.

### Expected

The compilation should succeed without manually modifying the build file.

## Environment

- Hardware Architecture: aarch64 on Apple M1
- Operating system: Mac OS Monterey 12.2.1

The following information is optional. Please provide them only if you have built from source.
- C++ Compiler version: 
```
Homebrew clang version 12.0.1
Target: arm64-apple-darwin21.3.0
Thread model: posix
InstalledDir: /opt/homebrew/opt/llvm@12/bin
```
- CMake version: cmake version 3.22.3
- CMake flags: `cmake -Bbuild -GNinja -DWASMEDGE_BUILD_PACKAGE="TGZ"`.
- Boost version: unknown

## Steps to Reproduce

Steps are following
1. Clone the source code. The commit id I was operating on is 8b8f3075ae79c4fa6d87ffdf6a4f64ce6a9b1c86 with data `Date:   Mon May 23 17:14:37 2022 +0800`
2. Install necessary dependency
```
brew install boost cmake ninja llvm@12
```
3. Export related env variable
```
export CC=/opt/homebrew/opt/llvm@12/bin/clang
export CXX=/opt/homebrew/opt/llvm@12/bin/clang++
export LDFLAGS="-L/opt/homebrew/opt/llvm@12/lib -Wl,-rpath,/opt/homebrew/opt/llvm@12/lib"
```
4. Run cmake
```
cmake -Bbuild -GNinja -DWASMEDGE_BUILD_PACKAGE="TGZ" .
```
5. Build project, and the failure should be reproduced.
```
cmake --build build
```
6. (optional) Manually modify the `./build/build.ninja` file as described above, and the compilation should succeed.

**Comment by hydai** [comment] 2022-05-25 05:22
Looks like this is a common issue when upgrading to MacOSX 12.x SDK: https://stackoverflow.com/questions/70287733/sdl2-doesnt-compile-on-macos-big-sur

Currently, I don't have a best practice to fix this. Do you have any workaround for this?

**Comment by wenym1** [comment] 2022-05-25 05:47
> Do you have any workaround for this?

Seems the problem is truly caused by the MacOS SDK version. 

Just tried adding a new option `-DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/` in cmake, and then the build worked without failure.

**Comment by hydai** [comment] 2023-06-11 08:52
Not sure if this is still available. I am not able to reproduce it anymore on my M2 macbook.

**Comment by hydai** [comment] 2023-10-28 20:18
Since there is an arm64 macOS CI runner, this issue no longer exists. Closing it.

**Closed by hydai** 2023-10-28 20:18 UTC
