### ISSUE TITLE
0.14.1 build failure on Debian (`error: call of overloaded ‘write<char>(fmt::v9::detail::default_arg_formatter`)

### ISSUE THREAD

**Issue by paravoid** [WasmEdge/WasmEdge#3782] opened 2024-09-19 14:51 UTC
### Summary

Trying to build 0.14.1 on an up-to-date Debian sid system results in this error:
```
[  9%] Built target utilBlake3
In file included from /home/paravoid/paravoid/wasmedge/upstream/include/common/int128.h:469,
                 from /home/paravoid/paravoid/wasmedge/upstream/include/common/spdlog.h:17,
                 from /home/paravoid/paravoid/wasmedge/upstream/include/common/enum_ast.hpp:22,
                 from /home/paravoid/paravoid/wasmedge/upstream/include/common/errinfo.h:16,
                 from /home/paravoid/paravoid/wasmedge/upstream/lib/common/errinfo.cpp:4:
/usr/include/fmt/format.h: In instantiation of ‘fmt::v9::detail::default_arg_formatter<Char>::iterator fmt::v9::detail::default_arg_formatter<Char>::operator()(T) [with T = __int128 unsigned; Char = char; iterator = fmt::v9::appender]’:
/usr/include/fmt/core.h:1639:15:   required from ‘constexpr decltype (vis(0)) fmt::v9::visit_format_arg(Visitor&&, const basic_format_arg<Context>&) [with Visitor = detail::default_arg_formatter<char>; Context = basic_format_context<appender, char>; decltype (vis(0)) = appender]’
 1639 |     return vis(detail::convert_for_visit(arg.value_.uint128_value));
      |            ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/format.h:4078:21:   required from ‘void fmt::v9::detail::vformat_to(buffer<T>&, fmt::v9::basic_string_view<Char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<typename std::conditional<std::is_same<typename fmt::v9::type_identity<T>::type, char>::value, fmt::v9::appender, std::back_insert_iterator<buffer<typename fmt::v9::type_identity<T>::type> > >::type, typename fmt::v9::type_identity<T>::type> >, locale_ref) [with Char = char; typename std::conditional<std::is_same<typename fmt::v9::type_identity<T>::type, char>::value, fmt::v9::appender, std::back_insert_iterator<buffer<typename fmt::v9::type_identity<T>::type> > >::type = fmt::v9::appender; typename fmt::v9::type_identity<T>::type = char]’
 4078 |     visit_format_arg(default_arg_formatter<Char>{out, args, loc}, arg);
      |     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/core.h:3215:21:   required from ‘OutputIt fmt::v9::vformat_to(OutputIt, string_view, format_args) [with OutputIt = std::back_insert_iterator<basic_memory_buffer<char> >; typename std::enable_if<detail::is_output_iterator<OutputIt, char>::value, int>::type <anonymous> = 0; string_view = basic_string_view<char>; format_args = basic_format_args<basic_format_context<appender, char> >]’
 3215 |   detail::vformat_to(buf, fmt, args, {});
      |   ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/core.h:3235:20:   required from ‘OutputIt fmt::v9::format_to(OutputIt, format_string<T ...>, T&& ...) [with OutputIt = std::back_insert_iterator<basic_memory_buffer<char> >; T = {const std::basic_string_view<char, std::char_traits<char> >&, const std::basic_string_view<char, std::char_traits<char> >&}; typename std::enable_if<detail::is_output_iterator<OutputIt, char>::value, int>::type <anonymous> = 0; format_string<T ...> = basic_format_string<char, const std::basic_string_view<char, std::char_traits<char> >&, const std::basic_string_view<char, std::char_traits<char> >&>]’
 3235 |   return vformat_to(out, fmt, fmt::make_format_args(args...));
      |          ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/paravoid/paravoid/wasmedge/upstream/include/common/types.h:664:19:   required from here
  664 |     fmt::format_to(std::back_inserter(Buffer), "{} {}"sv,
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  665 |                    WasmEdge::TypeCodeStr[Type.getCode()],
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  666 |                    WasmEdge::TypeCodeStr[Type.getHeapTypeCode()]);
      |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/format.h:3374:23: error: call of overloaded ‘write<char>(fmt::v9::detail::default_arg_formatter<char>::iterator&, __int128 unsigned&)’ is ambiguous
 3374 |     return write<Char>(out, value);
      |            ~~~~~~~~~~~^~~~~~~~~~~~
/usr/include/fmt/format.h:2218:20: note: candidate: ‘constexpr OutputIt fmt::v9::detail::write(OutputIt, T) [with Char = char; OutputIt = fmt::v9::appender; T = __int128 unsigned; typename std::enable_if<((is_integral<T>::value && (! std::is_same<T, bool>::value)) && (! std::is_same<T, Char>::value)), int>::type <anonymous> = 0]’
 2218 | FMT_CONSTEXPR auto write(OutputIt out, T value) -> OutputIt {
      |                    ^~~~~
/usr/include/fmt/format.h:3312:20: note: candidate: ‘constexpr OutputIt fmt::v9::detail::write(OutputIt, Char) [with Char = char; OutputIt = fmt::v9::appender]’
 3312 | FMT_CONSTEXPR auto write(OutputIt out, Char value) -> OutputIt {
      |                    ^~~~~
/usr/include/fmt/format.h:3341:20: note: candidate: ‘constexpr fmt::v9::enable_if_t<((bool)((((std::is_class<T>::value && (! fmt::v9::detail::is_string<T>::value)) && (! std::integral_constant<bool, (std::is_floating_point<T>::value || std::is_same<T, __float128>::value)>::value)) && (! std::is_same<T, Char>::value)) && (! std::is_same<const T&, decltype (fmt::v9::detail::arg_mapper<Context>().map(value))>::value))), OutputIt> fmt::v9::detail::write(OutputIt, const T&) [with Char = char; OutputIt = fmt::v9::appender; T = __int128 unsigned; Context = fmt::v9::basic_format_context<fmt::v9::appender, char>; fmt::v9::enable_if_t<((bool)((((std::is_class<T>::value && (! is_string<T>::value)) && (! std::integral_constant<bool, (std::is_floating_point<T>::value || std::is_same<T, __float128>::value)>::value)) && (! std::is_same<T, Char>::value)) && (! std::is_same<const T&, decltype (arg_mapper<Context>().map(value))>::value))), OutputIt> = fmt::v9::appender; decltype (arg_mapper<Context>().map(value)) = __int128 unsigned]’
 3341 | FMT_CONSTEXPR auto write(OutputIt out, const T& value) -> enable_if_t<
      |                    ^~~~~
make[2]: *** [lib/common/CMakeFiles/wasmedgeCommon.dir/build.make:104: lib/common/CMakeFiles/wasmedgeCommon.dir/errinfo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:614: lib/common/CMakeFiles/wasmedgeCommon.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```

Bisecting this reveals e1396de414c3d9f98c2a5a470354cabc8a3b9afb as the culprit.

I also tried patching `/usr/include/fmt/format.h` with cmake/0001-support-arithmetic-operations-in-uint128_fallback.patch, but that didn't work either. (Even if it did, it would not be something we could easily support in the Debian package.)

### Reproduction steps

1. Build with options `mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release  DWASMEDGE_BUILD_PLUGINS=OFF .. && make -j`

### Components

CLI

### WasmEdge Version or Commit you used

0.14.1

### Operating system information

Debian unstable

### Hardware Architecture

amd64

### Compiler flags and options

libfmt-dev 9.1.0+ds1-2

**Comment by hydai** [comment] 2024-09-19 15:09
Hi @ibmibmibm 
Debian still uses fmt v9 (Debian testing) and will never use our specific fmt version (v11) instead. To avoid this issue happens, we should:

1. Ensure our Debian testing CI will no longer use our bundled fmt to detect this kind of problem earlier.
2. Maybe we should have a patch for older fmt or change how we handle the v128 type in fmt.

**Comment by hydai** [comment] 2024-09-23 13:16
Hi @paravoid 

We are working on a patch to fix this issue, as some other users cannot access fmt v11 or apply our current patch for fmt v11. We need to figure out a new way to handle this situation. I will let you know once the new workaround is ready.

**Comment by hydai** [comment] 2024-09-30 09:35
Hi @paravoid 
We have a PR for this; please try to apply #3804 to see if the issue is resolved; thanks.

**Comment by hydai** [comment] 2024-09-30 17:00
Let me reopen this issue until the people from the Debian community confirm whether this patch is working or not.

**Comment by paravoid** [comment] 2024-10-04 18:24
I just tested it and it's working as intended. That patch looks neither simple nor small, so I really appreciate the fix and turnaround time here. Thank you so so much!

**Comment by hydai** [comment] 2024-10-04 19:29
Thanks, @paravoid, for the confirmation. I am closing this issue.

**Closed by hydai** 2024-10-04 19:29 UTC
Labels: bug, priority:high, c-Internal
