### ISSUE TITLE
bug: The LlamaEdge API server crashed suddenly.

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#3594] opened 2024-07-25 02:13 UTC
### Summary

The LlamaEdge API server suddenly crashed. After checking the log, the error message is as follows:

```
[2024-07-23 06:53:41.918] [wasi_logging_stdout] [info] chat_completions: rag_api_server::backend::ggml in src/backend/ggml.rs:481: Finish chat completions in non-stream mode
[2024-07-23 06:53:41.918] [wasi_logging_stdout] [info] rag_query_handler: rag_api_server::backend::ggml in src/backend/ggml.rs:508: Send the rag query response
[2024-07-23 06:53:41.919] [wasi_logging_stdout] [info] response: rag_api_server in src/main.rs:454: version: HTTP/1.1, body_size: 375, status: 200, is_informational: false, is_success: true, is_redirection: false, is_client_error: false, is_server_error: false
[2024-07-23 06:53:41.919] [error] [WASI-NN] GGML backend: Llama input is not set!
```

### Current State

After this error message, the LlamaEdge API server stoped.

### Reproduction steps

I'm not sure if we can reproduce the error with ease.

I'm running the Llama-3-8B model with a knowledge base on a GPU machine.

### Screenshots

![DESCRIPTION](LINK.png)

### Components

CLI

### WasmEdge Version or Commit you used

0.13.5

### Operating system information

Ubuntu 22.04.2 LTS

### Hardware Architecture

X86_64

**Comment by hydai** [comment] 2024-08-06 11:49
Since we are not able to reproduce this, closing it. Please provide more detailed reproduction steps.

**Closed by hydai** 2024-08-06 11:49 UTC
Labels: bug
