### ISSUE TITLE
bug: Infit Loop will not terminated in javascript

### ISSUE THREAD

**Issue by qomosoloto** [WasmEdge/WasmEdge#3021] opened 2023-11-07 09:35 UTC
### Summary

Infit Loop will not terminated in javascript

### Current State

When used  `os.sleep(4000)`, the time-limit worked.

### Expected State

infinit loop should be terminated with given `time-limit` option.

### Reproduction steps

```bash
1. Given a javascript:

import * as os from 'os';
import * as std from 'std';
function x(){
  while(true){}
  return 1;
}
x();
2. `wasmedge --time-limit 1000 --dir .:. wasmedge_quickjs.wasm a.js`
3. wasmedge process alway exist after timelimit.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Components

CLI

### WasmEdge Version or Commit you used

0.13.4

### Operating system information

manjaro

### Hardware Architecture

amd64

**Comment by hydai** [comment] 2023-11-07 10:09
Hi @qomosoloto 
Thanks for raising this. However, I cannot reproduce this.

![CleanShot 2023-11-07 at 18 08 23](https://github.com/WasmEdge/WasmEdge/assets/2776756/5fd1dfa5-d1ca-4c94-94a4-713b8eea410f)

**Comment by qomosoloto** [comment] 2023-11-07 12:40
I was confused , it never exit ...
![nerver-exit](https://github.com/WasmEdge/WasmEdge/assets/8132885/3b8f661d-23c3-4b3c-b354-781093d5cf3b)

**Comment by dannypsnl** [comment] 2023-11-27 05:37
@qomosoloto Would you like to try it in 0.13.5?

**Comment by jaykchen** [comment] 2024-03-10 02:43
#2593

**Comment by hydai** [comment] 2024-06-04 19:37
Because we cannot reproduce this issue, closing it now. Please feel free to re-open it if this issue still happens with the 0.14.0 release.

**Closed by hydai** 2024-06-04 19:37 UTC
Labels: question, Cannot-Reproduce
