### ISSUE TITLE
Add more WASI-NN examples using WasmEdge

### ISSUE THREAD

**Issue by alabulei1** [WasmEdge/WasmEdge#1726] opened 2022-08-05 11:02 UTC
## Motivation

 WasmEdge now supports the WASI-NN proposal with the OpenVINO backend after the 0.10.1 version is released. It's would be better to add more examples.

## Appendix

Submit a PR [here](https://github.com/second-state/WasmEdge-WASINN-examples)

**Comment by ashutosh887** [comment] 2023-03-19 18:18
@hydai Let me work on the issue

**Comment by Mash707** [comment] 2023-07-20 05:16
@hydai do we have to add examples

**Comment by Mash707** [comment] 2023-07-20 05:17
@hydai is this related to adding examples for openvino?

**Comment by hydai** [comment] 2023-07-20 05:24
Hi @Mash707 
Yes. This issue is related to add new examples for the WASI-NN OpenVINO backend

**Comment by Mash707** [comment] 2023-07-20 05:27
Also We should update the Openvino install script in the given repo Readme file. If you can raise a issue , I'll give a PR https://github.com/second-state/WasmEdge-WASINN-examples#openvino-installation

**Comment by Mash707** [comment] 2023-07-20 06:53
> Hi @Mash707 
> 
> Yes. This issue is related to add new examples for the WASI-NN OpenVINO backend

We also should update the Openvino install script in the given repo Readme file. If you can raise a issue , I'll give a PR https://github.com/second-state/WasmEdge-WASINN-examples#openvino-installation

The Readme files of the current examples are also currently referring to the 2021 version of OpenVino

**Comment by hydai** [comment] 2023-07-20 21:24
Hi @Mash707 
The issue is tracked in this one. Why do we need to raise a new issue again?

**Comment by Mash707** [comment] 2023-07-20 21:33
> Hi @Mash707 
> 
> The issue is tracked in this one. Why do we need to raise a new issue again?

Since this issue was regarding adding new examples but we should first update the install script of openvino and then work on the examples https://github.com/second-state/WasmEdge-WASINN-examples/blob/master/scripts/install_openvino.sh . So I thought we can raise a issue to update the script first and then add new examples.

**Comment by hydai** [comment] 2024-01-25 10:02
I don't think we need this issue anymore. Closing it.

**Closed by hydai** 2024-01-25 10:02 UTC
Labels: good first issue, Hacktoberfest
