### ISSUE TITLE
On Windows, an error occurred when i embedded wasm in my rust app

### ISSUE THREAD

**Issue by abc767234318** [WasmEdge/WasmEdge#1777] opened 2022-08-23 13:41 UTC
## Description

An error occurred when I embedded wasm in my rust application.
<img width="655" alt="Snipaste_2022-08-23_21-41-12" src="https://user-images.githubusercontent.com/51507451/186173526-944fbd1f-49c0-4691-865e-e603875111c8.png">

- Hardware Architecture: x86
- Operating system: windows

**Comment by hydai** [comment] 2022-08-23 15:20
Hi @apepkuss 
Could you help with this issue?

**Comment by abc767234318** [comment] 2022-08-24 02:11
> @abc767234318 Could you please check the version of `WasmEdge` you are using? Or, tell us the commit id if you build from the source. Thanks!

I'll give it later. I don't have my computer with me right now.

**Comment by abc767234318** [comment] 2022-08-25 12:39
> @abc767234318 Could you please check the version of `WasmEdge` you are using? Or, tell us the commit id if you build from the source. Thanks!

Here is the version I used.
```
[dependencies]
wasmedge-sys = "0.8.0"
wasmedge-sdk = "0.3.0"
wasmedge-types = "0.2.0"
```

**Comment by apepkuss** [comment] 2022-08-25 12:44
> > @abc767234318 Could you please check the version of `WasmEdge` you are using? Or, tell us the commit id if you build from the source. Thanks!
> 
> Here is the version I used.
> 
> ```
> [dependencies]
> wasmedge-sys = "0.8.0"
> wasmedge-sdk = "0.3.0"
> wasmedge-types = "0.2.0"
> ```

What about `libwasmedge_c.so` (for Linux) or `libwasmedge_c.dylib` (for MacOS)? The issue you mentioned should be caused by it.

**Comment by hydai** [comment] 2024-06-06 23:24
This issue is out of date, closing it. Please feel free to re-open it if this issue still exists in the latest version.

**Closed by hydai** 2024-06-06 23:24 UTC
Labels: help wanted, Hacktoberfest, platform-windows, binding-rust
