### ISSUE TITLE
LFX Mentorship (Jun-Aug, 2024): Create a search-enabled API server for local LLMs

### ISSUE THREAD

**Issue by juntao** [WasmEdge/WasmEdge#3372] opened 2024-04-28 10:35 UTC
## Summary

WasmEdge is a lightweight inference runtime for AI and LLM applications. The [LlamaEdge project](https://github.com/LlamaEdge) has developed an [OpenAI-compatible API server](https://github.com/LlamaEdge/LlamaEdge/tree/main/api-server) and a [server-side RAG app](https://llamaedge.com/docs/user-guide/server-side-rag) based on WasmEdge. 

In this project, we aim to use the LlamaEdge components to build a new API server that incorporates real-time Internet search results into LLM answers.

## Details

We will build a search-enabled API server that is similar to the [rag-api-server](https://github.com/LlamaEdge/rag-api-server) but with the following unique features:

* It will use the user question as the query to search Google first.
* The top search results are then added to the LLM conversation context as the `system_prompt`. It is the same way as vector search results are added to the context in the [rag-api-server](https://github.com/LlamaEdge/rag-api-server).
* Generate and return the server response.

The project will be written in Rust and compiled to WebAssembly to run inside WasmEdge. Qualified mentees need to demonstrate that they can make changes to the [rag-api-server](https://github.com/LlamaEdge/rag-api-server), and then build and deploy the updated API server.

## LFX

Expected outcome: An OpenAI-compatible local LLM API server that uses Google Search for supplemental context

Recommended skills:
- Rust language
- LlamaEdge

Mentor:
- Michael Yuan @juntao michael@secondstate.io

Application link: https://mentorship.lfx.linuxfoundation.org/project/0a4e08a1-3404-46fc-b0d0-5117ec4ec119

**Comment by suryyyansh** [comment] 2024-04-29 10:23
Hey junato, I'm interested in this Mmentorship. When will the pretest and application details be announced? Thanks.

**Comment by suryyyansh** [comment] 2024-04-29 10:23
Hey junato, I'm interested in this Mentorship. When will the pretest and application details be announced? Thanks.

**Comment by juntao** [comment] 2024-04-30 05:58
@suryyyansh Thank you so much for your interest. The application has not officially started. If you would like to get a headstart, I would ask you to build the [rag-api-server](https://github.com/LlamaEdge/rag-api-server) yourself and find something (code or docs) that you can improve upon.

**Comment by harsh-ps-2003** [comment] 2024-05-06 12:24
@juntao I was able to build the rag-api-server, but there are no issues to solve in the repository, and the code and docs seem good to me! Can you suggest some improvements that you want to prove my competency? Thanks

**Comment by suryyyansh** [comment] 2024-05-06 21:41
@juntao I managed to build the server and get it running just fine. I then tried to add the `chatbot-ui` frontend (how `LlamaEdge` does it), but quickly ran into a brick wall. The server produces no output, despite input being passed properly and embeddings being computed. 

Here's the [issue](https://github.com/LlamaEdge/rag-api-server/issues/3) I've opened on the `rag-api-server` project.

Awaiting input. In the meantime, I'll try to figure out the cause of this.

**Comment by debrupf2946** [comment] 2024-05-12 14:56
@juntao I am Debrup pursuing Engg at BITS Pilani, and a contributor at Keras, I like to solve NLP problems and have worked extensively with hugginface(transformers, PEFT, datasets), Langchain, Llama index(data injection and Indexing), Knowledge graphs(Neo4J), RAGs, Rust.
 I was also selected for GSoC in an LMM-Finetuning project, I find this project interesting and similar, and I want to contribute,take part in LFX-Mentorship program

**Comment by angad-singhh** [comment] 2024-05-19 13:06
### RAG-with different LLM:
In this, instead of using the default LLM model mentioned in docs [Llama-3-8B-Instruct-GGUF](https://huggingface.co/second-state/Llama-3-8B-Instruct-GGUF), I used the [Phi-3-mini-4k-instruct](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct) and [All-MiniLM-L6-v2-Embedding-GGU](https://huggingface.co/second-state/All-MiniLM-L6-v2-Embedding-GGUF) for embedding. Created the Qdrant instance running and used the default `paris.txt` as knowledge base for vector database. 

- Retrieving the context from knowledge base based on prompt
><img width="650" alt="Screenshot 2024-05-19 183347" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/9034f954-049e-499c-b710-3de52b70d2d3">


- RAG context is then merged into the systems message

><img width="650" alt="Screenshot 2024-05-19 183406" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/4ef4ad11-b7a6-4cd1-b562-a3297f0849cb">

- Finally output is generated based on RAG context + User Prompt
><img width="650" alt="Screenshot 2024-05-19 183433" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/a35ab1fe-9c6b-4b31-96f3-2b1472c6f127">

**Comment by angad-singhh** [comment] 2024-05-19 13:06
### RAG with different LLM and Custom Embedded-Knowledge Base
In this, I changed the LLM model to a smaller model : [TinyLlama-1.1B-Chat-v1.0](https://huggingface.co/second-state/TinyLlama-1.1B-Chat-v1.0-GGUF) and created a  small **custom** knowledge-base-embedding, on the topic Microsoft `microsoft.txt`.

**Here are the outputs:** 

- Custom Knowledge base for embedding 
><img width="650" alt="Screenshot 2024-05-19 182840" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/d55559e4-35bc-4a07-b50a-f3a851ab8a07">

- Retrieving the context from knowledge base based on prompt
><img width="650" alt="Screenshot 2024-05-19 172947" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/8f8c68bd-6d08-46cf-84c4-be0587881f48">


- RAG context is then merged into the systems message

><img width="650" alt="Screenshot 2024-05-19 173108" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/08a6624b-bb61-46c5-9dde-42785022edf9">

- Finally output is generated based on RAG context + User Prompt
><img width="650" alt="Screenshot 2024-05-19 182750" src="https://github.com/WasmEdge/WasmEdge/assets/108326021/7859a713-90cf-4b69-b5f0-e0fda2c13c35">

**Comment by angad-singhh** [comment] 2024-05-19 15:24
@juntao , I'm also working on my own RAG-API-Server from scratch, will update you with progress soon. Meanwhile I'm also trying explore all other LFX projects too, to get an overview of whole, Wasm Edge ecosystem so that I could contribute to Wasm Edge even after LFX duration.

**Comment by juntao** [comment] 2024-05-20 06:42
> @juntao I was able to build the rag-api-server, but there are no issues to solve in the repository, and the code and docs seem good to me! Can you suggest some improvements that you want to prove my competency for the LFX Mentorship? Thanks

Perhaps you could create a video recording to show how it works? Thanks.  @harsh-ps-2003

**Comment by suryyyansh** [comment] 2024-05-20 07:13
Hey @juntao I had my [PR](https://github.com/LlamaEdge/rag-api-server/pull/5) merged on this [issue](https://github.com/LlamaEdge/rag-api-server/issues/3), and have implemented functionality to assert that the qdrant service is currently active when running the server on my local fork.

I'm currently working on implementing an interface to work with different search APIs ([You API](https://documentation.you.com/openai-language-model-integration), [Tavily](https://docs.tavily.com/docs/tavily-api/introduction), etc..) in a similar vein to the plugin system for wasi-nn. 

Is there anything else I should be doing? please let me know

**Comment by DhruvSinghiitmandi** [comment] 2024-05-20 16:11
Hey @juntao 
I am Dhruv Singh , pursuing my bachelors at IIT Mandi in Computer Science. 
I have some experience with LLMs(finetuning ) and building backend for RAG based Applications . I'm interested in this project, currently I have built the code successfully and run locally. Initially i faced some issue in getting the server to run as qdrant service was not running (not mentioned in the readme ). I have already begin integrating the server with tavily API for now . I have made a different endpoint for retrieval through web. Currently I'm facing some issues in the build processs but I'm actively working on it. Is there anything more I should be doing now?

**Comment by suryyyansh** [comment] 2024-05-22 21:50
@juntao I've finished implementing the search-enabled rag-api-server, It's available [here](https://github.com/suryyyansh/search-enabled-rag-llamaedge/). The github actions don't pass because I didn't compile against clippy. 

(It still compiles fine without warnings normally, though)

Here is an example of the search results being fetched:
![search_results](https://github.com/WasmEdge/WasmEdge/assets/118013430/69930652-7671-4ef5-808a-a34d5bc7343e)

And here, chat completion uses the search results as context:
![curl_rag_search_example](https://github.com/WasmEdge/WasmEdge/assets/118013430/728bd0e4-b657-4978-badb-832b97d7f45f)

My implementation relies on a new trait called Query. New APIs can be introduced by implementing the search function provided by this trait. For demonstration purposes, the use of Tavily has been hardcoded, but can be changed to be decided at runtime.

The search functionality can be invoked either:
1. manually, prepending their message with "[SEARCH]", or
2. dynamically, by asking a question with no suitable qdrant embeddings.

Hope this is enough to prove my competence for the mentorship!

**Closed** 2024-09-03 20:18 UTC
Labels: enhancement, LFX Mentorship
