### ISSUE TITLE
AOT bug when using ctr 

### ISSUE THREAD

**Issue by GhazalSdn** [WasmEdge/WasmEdge#2372] opened 2023-03-21 19:07 UTC
## Description
Having difficulty running OCI images created from AOT wasm modules.

### Current State

I created an AOT wasm module using Wasmedge, however, when I use CTR(using runwasi) to  run the OCI image created from that AOT wasm, I get this error:

`[error]execution failed: out of bounds memory access, Code: 0x88`
`[error]When executing module name: “main”, function name: “_start"`

But when I run the same image on other machines, it is working fine. Just having this problem in the same machine in which  AOT wasm is created.

### Expected

Running the OCI image in the same machine the AOT wasm is created.

## Environment

The machine I created AOT wasm: 
ubuntu x86 architecture(using runwasi in CTR)
I tried on both MacOS Intel(using WASM support in Docker desktop) and ubuntu ARM(using runwasi in CTR), and they were working fine with the same image.

**Comment by alabulei1** [comment] 2023-03-22 02:28
@hydai Could you please take  a look?

**Comment by hydai** [comment] 2023-06-16 09:47
Sorry for the late response. @GhazalSdn Could you share your wasm image so I can reproduce the situation on my environment?

**Comment by hydai** [comment] 2024-06-04 19:56
Because we didn't receive the problematic wasm image, closing this. Please feel free to re-open it with more information. Thanks.

**Closed by hydai** 2024-06-04 19:56 UTC
Labels: integration, c-Container, c-AOT, Cannot-Reproduce
