### ISSUE TITLE
Fails to build with GCC 14

### ISSUE THREAD

**Issue by siretart** [WasmEdge/WasmEdge#3640] opened 2024-08-11 14:55 UTC
### Summary

Debian has upgraded GCC version to default to gcc 14. Unfortunately, this makes the wasmedge package failing to build because of newly introduced warnings:

```
[ 34%] Building CXX object lib/aot/CMakeFiles/wasmedgeAOT.dir/cache.cpp.o
cd /<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/lib/aot && /usr/bin/c++ -DFMT_SHARED -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/include -I/<<PKGBUILDDIR>>/thirdparty/blake3 -I/<<PKGBUILDDIR>>/include -I/<<PKGBUILDDIR>>/obj-x86_64-linux-gnu/lib/system -isystem /usr/lib/llvm-16/include -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -fcf-protection -Wdate-time -D_FORTIFY_SOURCE=2 -std=c++17 -fPIC -fvisibility=hidden -fvisibility-inlines-hidden  -fno-exceptions -Wall -Wextra -Werror -Wno-error=pedantic -Wno-error=dangling-reference -Wno-psabi -MD -MT lib/aot/CMakeFiles/wasmedgeAOT.dir/cache.cpp.o -MF CMakeFiles/wasmedgeAOT.dir/cache.cpp.o.d -o CMakeFiles/wasmedgeAOT.dir/cache.cpp.o -c /<<PKGBUILDDIR>>/lib/aot/cache.cpp
In file included from /usr/include/c++/14/vector:66,
                 from /usr/include/c++/14/functional:64,
                 from /usr/include/spdlog/common.h:16,
                 from /usr/include/spdlog/spdlog.h:12,
                 from /<<PKGBUILDDIR>>/include/common/log.h:18,
                 from /<<PKGBUILDDIR>>/include/common/enum_errcode.hpp:18,
                 from /<<PKGBUILDDIR>>/include/common/errcode.h:16,
                 from /<<PKGBUILDDIR>>/include/loader/filemgr.h:17,
                 from /<<PKGBUILDDIR>>/lib/loader/filemgr.cpp:4:
In destructor ‘std::_Vector_base<_Tp, _Alloc>::~_Vector_base() [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’,
    inlined from ‘std::vector<_Tp, _Alloc>::~vector() [with _Tp = unsigned char; _Alloc = std::allocator<unsigned char>]’ at /usr/include/c++/14/bits/stl_vector.h:738:7,
    inlined from ‘constexpr void std::_Optional_payload_base<_Tp>::_M_destroy() [with _Tp = std::vector<unsigned char>]’ at /usr/include/c++/14/optional:283:35,
    inlined from ‘constexpr void std::_Optional_payload_base<_Tp>::_M_reset() [with _Tp = std::vector<unsigned char>]’ at /usr/include/c++/14/optional:314:14,
    inlined from ‘constexpr void std::_Optional_base_impl<_Tp, _Dp>::_M_reset() [with _Tp = std::vector<unsigned char>; _Dp = std::_Optional_base<std::vector<unsigned char>, false, false>]’ at /usr/include/c++/14/optional:466:53,
    inlined from ‘std::enable_if_t<((bool)is_constructible_v<_Tp, _Args ...>), _Tp&> std::optional<_Tp>::emplace(_Args&& ...) [with _Args = {std::vector<unsigned char, std::allocator<unsigned char> >}; _Tp = std::vector<unsigned char>]’ at /usr/include/c++/14/optional:915:18,
    inlined from ‘WasmEdge::Expect<void> WasmEdge::FileMgr::setCode(std::vector<unsigned char>)’ at /<<PKGBUILDDIR>>/lib/loader/filemgr.cpp:52:21:
/usr/include/c++/14/bits/stl_vector.h:369:59: error: ‘((std::_Vector_base<unsigned char, std::allocator<unsigned char> >*)((char*)this + 8))[2].std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_impl.std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_impl::std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_impl_data.std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_impl_data::_M_start’ may be used uninitialized [-Werror=maybe-uninitialized]
  369 |                       _M_impl._M_end_of_storage - _M_impl._M_start);
      |                                                   ~~~~~~~~^~~~~~~~
/usr/include/c++/14/bits/stl_vector.h:369:31: error: ‘((std::_Vector_base<unsigned char, std::allocator<unsigned char> >*)((char*)this + 8))[2].std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_M_impl.std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_impl::std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_impl_data.std::_Vector_base<unsigned char, std::allocator<unsigned char> >::_Vector_impl_data::_M_end_of_storage’ may be used uninitialized [-Werror=maybe-uninitialized]
  369 |                       _M_impl._M_end_of_storage - _M_impl._M_start);
      |                       ~~~~~~~~^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [lib/loader/CMakeFiles/wasmedgeLoaderFileMgr.dir/build.make:79: lib/loader/CMakeFiles/wasmedgeLoaderFileMgr.dir/filemgr.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
```

Seems that gcc14 thinks that the vector in https://github.com/WasmEdge/WasmEdge/blob/0.13.5/lib/loader/filemgr.cpp#L50-L57 could end up uninitialized. 

### Appendix

- http://qa-logs.debian.net/2024/07/01/wasmedge_0.13.5+dfsg-1_unstable_gccexp.log
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1075633

**Comment by q82419** [comment] 2024-08-12 09:33
Hi @siretart ,

I tested with `0.13.5` and updated `spdlog` and `fmt` dependency, but cannot reproduce this issue with `gcc-14`.

cc @hydai

**Comment by diederikdehaas** [comment] 2024-08-12 10:53
> We currently use debian:testing, however, it still uses gcc 13 and it doesn't trigger this error. Is there any choice that we can use for verifying the latest changes that Debian does for the default toolchain?

The default GCC version in Testing is 14 since *today*, so if you try again or later today or tomorrow, it should use GCC 14.

I don't know if there's also a ``debian:unstable`` Docker image, but if so, you could add that to the mix?  
Possibly with some relaxed rules so that you will be informed about (breaking) changes, but it doesn't immediately block everything? (I'm not familiar (enough) with how you work, so this is just a general comment)

**Comment by hydai** [comment] 2024-08-12 14:14
> The default GCC version in Testing is 14 since _today_, so if you try again or later today or tomorrow, it should use GCC 14.

The docker image is updated. We can install the GCC 14 as the default toolchain now. So I think it's fine for us to keep using `debian:testing`.

**Comment by hydai** [comment] 2024-08-12 15:02
> I tested with `0.13.5` and updated `spdlog` and `fmt` dependency, but cannot reproduce this issue with `gcc-14`. Related fix for `0.13.5` is at #3644 .

What's the GCC version you used? I found that the failed version is 14.1.0. I am not sure if you are using the same version as the failed one.

**Comment by siretart** [comment] 2024-08-12 15:36
FWIW, Debian/testing comes with gcc-14.2. Looking at #3644, I'd be surprised if that was sufficient to fix the build. I would have expected a code change in `lib/loader/*`

**Comment by hydai** [comment] 2024-08-12 17:29
We found that upgrading the fmt library to 11 with our master branch(after 0.14.1-rc.1) can pass the compilation on `debian:testing`. And it did use gcc 14.2. See: https://github.com/WasmEdge/WasmEdge/actions/runs/10349195854/job/28643113694?pr=3643

Since our package on Debian is still using 0.13.5, we are going to check the behavior and create a patch for it.

cc @q82419 Please ensure we are using gcc14.2 to build and verify.

**Comment by diederikdehaas** [comment] 2024-08-12 19:12
> I tested with 0.13.5 and updated spdlog and fmt dependency, but cannot reproduce this issue with gcc-14.
Related fix for 0.13.5 is at https://github.com/WasmEdge/WasmEdge/pull/3644 .

Is that the 0.13.5 tag or the 0.13.5_ggml_lts branch? Because there are [quite some differences](https://github.com/WasmEdge/WasmEdge/compare/0.13.5...0.13.5_ggml_lts)

**Comment by hydai** [comment] 2024-08-12 21:11
I found some interesting things. Here is the dockerfile I used for reproducing the problem:

```dockerfile
FROM debian:testing

RUN apt update && apt upgrade -y && apt install -y \
	software-properties-common \
	wget \
	cmake \
	ninja-build \
	curl \
	git \
	dpkg-dev \
	llvm-dev \
	liblld-dev \
	gcc \
	g++ \
	rpm \
	dpkg-dev \
	libspdlog-dev

WORKDIR /
RUN git clone --depth 1 --branch 0.13.5 https://github.com/WasmEdge/WasmEdge.git
RUN git config --global --add safe.directory /WasmEdge
WORKDIR /WasmEdge
RUN cmake -Bbuild \
	-GNinja \
	-DCMAKE_BUILD_TYPE=Release \
	-DWASMEDGE_BUILD_PLUGINS=OFF \
	-DWASMEDGE_BUILD_PACKAGE="TGZ" .
RUN cmake --build build
RUN ./build/tools/wasmedge/wasmedge --version
```

I used the 0.13.5 tag with the option'- DWASMEDGE_BUILD_PLUGINS=OFF' that I saw in the Debian failed log.
And even if I didn't apply any patch to our 0.13.5 tag, it can be built without any issue. I would like to know if we can run some commands to reproduce the error issue. Does the Debian CI do something special to set up the environment?

Here is the full log that I built without any issue: https://gist.github.com/hydai/17b3f0c5eb46a0b44a372d68ad5f52be

**Comment by hydai** [comment] 2024-08-12 21:14
> Is that the 0.13.5 tag or the 0.13.5_ggml_lts branch? Because there are [quite some differences](https://github.com/WasmEdge/WasmEdge/compare/0.13.5...0.13.5_ggml_lts)

0.13.5_ggml_lts is another branch we maintained for releasing the ggml plugin for 0.13.5. To reduce the situation, let's focus on the 0.13.5 tag.

**Comment by hydai** [comment] 2024-08-12 21:21
PR #3644 fixes the warnings triggered by GCC 14 when we try to use the spdlog version specified in the CMakeList file. But I found that `libspdlog-dev` uses `fmt9` on Debian/testing, which is an older version than the one we use. So, I am afraid that PR #3644 is not fixing the same problem we encountered on the reported Debian CI.

**Comment by q82419** [comment] 2024-08-13 07:54
Hi @siretart  @diederikdehaas ,

I tested with `debian:testing` and install the following packages:

```bash
$ apt-get update -y
$ apt-get install --no-install-recommends -y lsb-release software-properties-common curl wget gnupg cmake ninja-build git xz-utils llvm-dev zlib1g-dev libzstd-dev liblld-dev g++
```

And  checkout the tag `0.13.5` with the following patch:

```
diff --git a/lib/common/CMakeLists.txt b/lib/common/CMakeLists.txt
index 7207ec08..df8970fd 100644
--- a/lib/common/CMakeLists.txt
+++ b/lib/common/CMakeLists.txt
@@ -1,32 +1,36 @@
 # SPDX-License-Identifier: Apache-2.0
 # SPDX-FileCopyrightText: 2019-2022 Second State INC

+
 find_package(spdlog QUIET)
 if(spdlog_FOUND)
 else()
   FetchContent_Declare(
-    spdlog
-    GIT_REPOSITORY https://github.com/gabime/spdlog.git
-    GIT_TAG        v1.11.0
+    fmt
+    GIT_REPOSITORY https://github.com/fmtlib/fmt.git
+    GIT_TAG        11.0.2
     GIT_SHALLOW    TRUE
   )
-  set(SPDLOG_BUILD_SHARED OFF CACHE BOOL "Build shared library" FORCE)
+  set(FMT_INSTALL OFF CACHE BOOL "Generate the install target." FORCE)
+  FetchContent_MakeAvailable(fmt)
+  wasmedge_setup_target(fmt)
   if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
-    get_property(
-      compile_options
-      DIRECTORY
-      PROPERTY COMPILE_OPTIONS
-    )
-    set_property(
-      DIRECTORY
-      APPEND
-      PROPERTY COMPILE_OPTIONS
-      ${WASMEDGE_CFLAGS}
+    target_compile_options(fmt
+      PUBLIC
       -Wno-missing-noreturn
-      -Wno-missing-variable-declarations
+      PRIVATE
+      -Wno-sign-conversion
     )
-    unset(compile_options)
   endif()
+
+  FetchContent_Declare(
+    spdlog
+    GIT_REPOSITORY https://github.com/gabime/spdlog.git
+    GIT_TAG        v1.13.0
+    GIT_SHALLOW    TRUE
+  )
+  set(SPDLOG_BUILD_SHARED OFF CACHE BOOL "Build shared library" FORCE)
+  set(SPDLOG_FMT_EXTERNAL ON  CACHE BOOL "Use external fmt library instead of bundled" FORCE)
   FetchContent_MakeAvailable(spdlog)
   wasmedge_setup_target(spdlog)
 endif()
diff --git a/lib/common/errinfo.cpp b/lib/common/errinfo.cpp
index 69aa6669..90d9807c 100644
--- a/lib/common/errinfo.cpp
+++ b/lib/common/errinfo.cpp
@@ -5,6 +5,9 @@
 #include "common/errcode.h"
 #include "common/hexstr.h"

+#include <spdlog/fmt/fmt.h>
+#include <spdlog/fmt/ranges.h>
+
 using namespace std::literals;

 fmt::format_context::iterator
```

Build with the command in the source directory:

```bash
$ cmake -Bbuild -GNinja .
$ cmake --build build
```

It works well.

cc @hydai

**Comment by hydai** [comment] 2024-08-14 10:19
Hi @siretart and @diederikdehaas 
And back to the original problem, I think it's fine to disable this warning `maybe-uninitialized` to avoid failing the building process.
However, we (@hydai and @q82419) are not able to reproduce the error you reported. You can find that our patch is fixing the libfmt issue because the only error we can reproduce is all about the fmt/spdlog will fail during the compilation.

**Comment by diederikdehaas** [comment] 2024-08-14 12:45
> 0.13.5_ggml_lts is another branch we maintained for releasing the ggml plugin for 0.13.5. To reduce the situation, let's focus on the 0.13.5 tag.

Agreed. My question was about verifying assumptions and making sure we weren't comparing different things.

**Comment by diederikdehaas** [comment] 2024-08-14 12:53
> And checkout the tag 0.13.5 with the following patch:

I did include *a* patch, but I'll try to verify if it's complete (enough).
In case it helps, here's a CI pipeline run where the build fails:  
https://salsa.debian.org/diederik/wasmedge/-/pipelines/715340

Maybe you could check if you see any problems?

> And back to the original problem, I think it's fine to disable this warning maybe-uninitialized to avoid failing the building process.

Agreed, especially since you haven't been able to reproduce it.

**Comment by PeterD1524** [comment] 2024-08-14 17:55
FWIW, the CI is building with `-DCMAKE_BUILD_TYPE=None` and it somehow uses `-O2`.
`-DCMAKE_BUILD_TYPE=Release` adds `-O3`.
Use `-DCMAKE_BUILD_TYPE=None` and add `CXXFLAGS=-O2` will get the same error.

Modified Dockerfile from above to get the error:
```dockerfile
FROM debian:testing

RUN apt update && apt upgrade -y && apt install -y \
	software-properties-common \
	wget \
	cmake \
	ninja-build \
	curl \
	git \
	dpkg-dev \
	llvm-dev \
	liblld-dev \
	gcc \
	g++ \
	rpm \
	dpkg-dev \
	libspdlog-dev

WORKDIR /
RUN git clone --depth 1 --branch 0.13.5 https://github.com/WasmEdge/WasmEdge.git
RUN git config --global --add safe.directory /WasmEdge
WORKDIR /WasmEdge
RUN CXXFLAGS=-O2 cmake -Bbuild \
	-GNinja \
	-DCMAKE_BUILD_TYPE=None \
	-DWASMEDGE_BUILD_PLUGINS=OFF \
	-DWASMEDGE_BUILD_PACKAGE="TGZ" .
RUN cmake --build build
RUN ./build/tools/wasmedge/wasmedge --version
```

**Comment by paravoid** [comment] 2024-08-14 18:38
For what it's worth, this is also the case with 0.14.0 (which I'm working on uploading to Debian).

**Comment by hydai** [comment] 2024-08-14 18:54
Thanks for @PeterD1524 
So the behavior is totally different between `-O2` and `-O3`. I can reproduce it now.

I am unsure why GCC 14 asks for this in `-O2` but does not require it in `-O3`. Anyway, I have a patch to fix this issue below. After applying this patch, it will do a redundant copy for the copy-by-value vector again, so I expect that we will consume extra memory and time when calling the `setCode` function.

```
From 345a3d7809548718bf8e36107ab00a18c208600d Mon Sep 17 00:00:00 2001
From: hydai <hydai@secondstate.io>
Date: Thu, 15 Aug 2024 02:50:51 +0800
Subject: [PATCH] [Loader] Fix GCC 14 maybe-uninitialized warning

Signed-off-by: hydai <hydai@secondstate.io>
---
 lib/loader/filemgr.cpp | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/lib/loader/filemgr.cpp b/lib/loader/filemgr.cpp
index 775d962f..48e0c009 100644
--- a/lib/loader/filemgr.cpp
+++ b/lib/loader/filemgr.cpp
@@ -49,7 +49,8 @@ Expect<void> FileMgr::setCode(Span<const Byte> CodeData) {
 // Set code data. See "include/loader/filemgr.h".
 Expect<void> FileMgr::setCode(std::vector<Byte> CodeData) {
   reset();
-  DataHolder.emplace(std::move(CodeData));
+  std::vector<Byte> Copy = CodeData;
+  DataHolder.emplace(std::move(Copy));
   Data = DataHolder->data();
   Size = DataHolder->size();
   Status = ErrCode::Value::Success;
--
2.34.1

```

**Comment by hydai** [comment] 2024-08-14 19:08
This is another patch that only turns off this warning inside the loader for GCC 14.
Personally, I prefer this one, but I will wait for the response from @ibmibmibm and @q82419.

```
From a59b7be127041fe559fe1c46503b2ad34448f853 Mon Sep 17 00:00:00 2001
From: hydai <hydai@secondstate.io>
Date: Thu, 15 Aug 2024 03:05:59 +0800
Subject: [PATCH] [Loader] Fix GCC 14 maybe-uninitialized warning

Signed-off-by: hydai <hydai@secondstate.io>
---
 lib/loader/CMakeLists.txt | 7 +++++++
 1 file changed, 7 insertions(+)

diff --git a/lib/loader/CMakeLists.txt b/lib/loader/CMakeLists.txt
index 21bc5730..e974941e 100644
--- a/lib/loader/CMakeLists.txt
+++ b/lib/loader/CMakeLists.txt
@@ -7,6 +7,13 @@ wasmedge_add_library(wasmedgeLoaderFileMgr
   aot_section.cpp
 )

+if (CMAKE_COMPILER_IS_GNUCC AND CMAKE_CXX_COMPILER_VERSION VERSION_GREATER_EQUAL 14)
+  target_compile_options(wasmedgeLoaderFileMgr
+    PRIVATE
+    -Wno-maybe-uninitialized
+    )
+endif()
+
 target_link_libraries(wasmedgeLoaderFileMgr
   PUBLIC
   wasmedgeCommon
--
2.34.1

```

**Comment by PeterD1524** [comment] 2024-08-14 19:14
This also works. Maybe this is a gcc bug?

```c++
Expect<void> FileMgr::setCode(std::vector<Byte> CodeData) {
  for (auto I = 0; I < 2; ++I) {
    if (I == 0) {
      reset();
    }
  }
  DataHolder.emplace(std::move(CodeData));
  Data = DataHolder->data();
  Size = DataHolder->size();
  Status = ErrCode::Value::Success;
  return {};
}
```

**Comment by PeterD1524** [comment] 2024-08-15 00:12
Sorry I think I made a mistake. `-O3` itself produces the error, too.
The problem is `-DCMAKE_BUILD_TYPE=Release` adds `-O3` and also `-flto=auto`.
`-flto=auto` is added probably because [cmake/Helper.cmake](https://github.com/WasmEdge/WasmEdge/blob/0.13.5/cmake/Helper.cmake) does set_target_properties INTERPROCEDURAL_OPTIMIZATION when CMAKE_BUILD_TYPE=Release.
https://github.com/WasmEdge/WasmEdge/blob/b8eb435507efb98fa8a799257795fcd9f8440975/cmake/Helper.cmake#L4-L17
https://github.com/WasmEdge/WasmEdge/blob/b8eb435507efb98fa8a799257795fcd9f8440975/cmake/Helper.cmake#L120-L131
`-O3` and `-flto=auto` combined does not produce the error.

Here is a minimal example to produce the -Werror=maybe-uninitialized error.
main.cc:

```c++
#include <optional>
#include <vector>

void setCode(std::optional<std::vector<int>> DataHolder) {
  DataHolder.reset();
  DataHolder.emplace();
}

int main() {}

```

Compile with `c++ -O1 -std=c++17 -Werror=maybe-uninitialized main.cc` produces the error. `-O1`, `-O2`, `-O3` all produce the error.
Adding `-fno-inline` or `-flto=auto` does not produce the error.

https://github.com/WasmEdge/WasmEdge/blob/b8eb435507efb98fa8a799257795fcd9f8440975/lib/loader/filemgr.cpp#L50-L57

`FileMgr::reset` calls `DataHolder.reset` which may call `std::vector`'s destructor (which includes the part gcc thinks has -Werror=maybe-uninitialized) and `DataHolder.emplace` internally calls something similiar to `DataHolder.reset` which may call `std::vector`'s destructor. This is similiar to the example above.

**Comment by PeterD1524** [comment] 2024-08-15 00:14
Sorry I think I made a mistake. `-O3` itself produces the error, too.
The problem is `-DCMAKE_BUILD_TYPE=Release` adds `-O3` and also `-flto=auto`.
`-flto=auto` is added probably because [cmake/Helper.cmake](https://github.com/WasmEdge/WasmEdge/blob/0.13.5/cmake/Helper.cmake) does set_target_properties INTERPROCEDURAL_OPTIMIZATION when CMAKE_BUILD_TYPE=Release.
https://github.com/WasmEdge/WasmEdge/blob/b8eb435507efb98fa8a799257795fcd9f8440975/cmake/Helper.cmake#L4-L17
https://github.com/WasmEdge/WasmEdge/blob/b8eb435507efb98fa8a799257795fcd9f8440975/cmake/Helper.cmake#L120-L131
`-O3` and `-flto=auto` combined does not produce the error.

Here is a minimal example to produce the -Werror=maybe-uninitialized error.
main.cc:

```c++
#include <optional>
#include <vector>

void setCode(std::optional<std::vector<int>> DataHolder) {
  DataHolder.reset();
  DataHolder.emplace();
}

int main() {}

```

Compile with `c++ -O1 -std=c++17 -Werror=maybe-uninitialized main.cc` produces the error. `-O1`, `-O2`, `-O3` all produce the error.
Adding `-fno-inline` or `-flto=auto` does not produce the error.

https://github.com/WasmEdge/WasmEdge/blob/b8eb435507efb98fa8a799257795fcd9f8440975/lib/loader/filemgr.cpp#L50-L57

`FileMgr::reset` calls `DataHolder.reset` which may call `std::vector`'s destructor (which includes the part gcc thinks has -Werror=maybe-uninitialized) and `DataHolder.emplace` internally calls something similiar to `DataHolder.reset` which may call `std::vector`'s destructor. This is similiar to the example above.

**Comment by hydai** [comment] 2024-08-15 05:04
Thanks @PeterD1524 

After discussing with @ibmibmibm, we would use the following patch to fix this false positive warning:

```
From a6d804ba939037053804a7569f14859379d0da0e Mon Sep 17 00:00:00 2001
From: hydai <hydai@secondstate.io>
Date: Thu, 15 Aug 2024 13:01:19 +0800
Subject: [PATCH] [Loader] Fix GCC 14 maybe-uninitialized warning

Signed-off-by: hydai <hydai@secondstate.io>
---
 lib/loader/filemgr.cpp | 5 +++++
 1 file changed, 5 insertions(+)

diff --git a/lib/loader/filemgr.cpp b/lib/loader/filemgr.cpp
index 775d962f..f25f3eed 100644
--- a/lib/loader/filemgr.cpp
+++ b/lib/loader/filemgr.cpp
@@ -49,6 +49,11 @@ Expect<void> FileMgr::setCode(Span<const Byte> CodeData) {
 // Set code data. See "include/loader/filemgr.h".
 Expect<void> FileMgr::setCode(std::vector<Byte> CodeData) {
   reset();
+  // Tell GCC 14 that DataHolder has no data.
+  // Fix the false positive warning,
+  // which is reported by GCC 14 with `maybe-uninitialized`
+  assuming(!DataHolder);
+
   DataHolder.emplace(std::move(CodeData));
   Data = DataHolder->data();
   Size = DataHolder->size();
--
2.34.1

```

This will tell GCC 14 that DataHolder has no data, so it's totally fine to call `emplace` after the `reset` function. I will raise a PR for this later.

**Comment by hydai** [comment] 2024-08-15 06:00
The patch is merged into the master branch. Please use the last patch for fixing this problem.

**Comment by diederikdehaas** [comment] 2024-08-15 09:44
The build now succeeds \o/ https://salsa.debian.org/diederik/wasmedge/-/pipelines/716827

(There are still some issues, but I'm 99% sure those are Debian issues)

**Comment by hydai** [comment] 2024-08-15 11:50
Thanks, @diederikdehaas, for the confirmation.  
This patch can also be applied to 0.14.0.

**Comment by hydai** [comment] 2024-08-28 04:52
I saw that the bug is marked as resolved in the Debian Bug report system[1]. I am closing this. Please feel free to raise a new issue or reopen this if there are any related problems. Thank you for all your assistance :-).

[1]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1075633

**Closed by hydai** 2024-08-28 04:52 UTC
Labels: bug, question, v-0.14.1
