### ISSUE TITLE
Symbol Lookup error while running Pytorch AI Inference example

### ISSUE THREAD

**Issue by eshaanagarwal** [WasmEdge/WasmEdge#2594] opened 2023-06-14 17:30 UTC
## Description
As part of my work, I was trying to run the Pytorch AI inference sample example at https://wasmedge.org/docs/develop/rust/ai_inference/pytorch/ but I am facing the following error of symbol look up.

### Current State

```bash
eshaan@eshaan:~/Desktop/cncf/WasmEdge-WASINN-examples/pytorch-mobilenet-image$ wasmedge --dir .:. wasmedge-wasinn-example-mobilenet-image.wasm mobilenet.pt input.jpg
Read torchscript binaries, size in bytes: 14376860
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
wasmedge: symbol lookup error: /home/eshaan/.wasmedge/lib/../plugin/libwasmedgePluginWasiNN.so: undefined symbol: _ZNK5torch3jit6Object11find_methodERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

### Expected

As part of the example, I should have received the following output. 
```bash
Read torchscript binaries, size in bytes: 14376924
Loaded graph into wasi-nn with ID: 0
Created wasi-nn execution context with ID: 0
Read input tensor, size in bytes: 602112
Executed graph inference
   1.) [954](20.6681)banana
   2.) [940](12.1483)spaghetti squash
   3.) [951](11.5748)lemon
   4.) [950](10.4899)orange
   5.) [953](9.4834)pineapple, bananas
```

## Environment
- Hardware Architecture: (x86\_64 )
- Operating system: (Ubuntu 20.04 )

I have tried to build from source. 

- C++ Compiler version: 9.4 
- CMake version: 3.22.1
- CMake flags: -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="PyTorch" .. && make -j
- Boost version: libboost1.71-dev:amd64

## Steps to Reproduce
```
git clone https://github.com/WasmEdge/WasmEdge.git
cd WasmEdge
sudo apt install -y \
   software-properties-common \
   cmake \
   libboost-all-dev

sudo apt install -y \
   llvm-12-dev \
   liblld-12-dev

sudo apt install -y gcc g++
```
Then inside the repository 
```
export PYTORCH_VERSION="1.8.2"
curl -s -L -O --remote-name-all https://download.pytorch.org/libtorch/lts/1.8/cpu/libtorch-cxx11-abi-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip
unzip -q "libtorch-cxx11-abi-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip"
rm -f "libtorch-cxx11-abi-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip"
export LD_LIBRARY_PATH=$(pwd)/libtorch/lib:${LD_LIBRARY_PATH}
export Torch_DIR=$(pwd)/libtorch
```
and then 
```
mkdir -p build && cd build
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="PyTorch" .. && make -j
# For the WASI-NN plugin, you should install this project.
sudo cmake --install .
```

**Comment by hydai** [comment] 2023-06-14 17:36
Hi @eshaanagarwal 
Could you please recheck the CMake version? It's not possible to be 9.4.

Also, could you create a dockerfile to reproduce your issue?

**Comment by eshaanagarwal** [comment] 2023-06-14 17:42
> Hi @eshaanagarwal Could you please recheck the CMake version? It's not possible to be 9.4.
> 
> Also, could you create a dockerfile to reproduce your issue?

Apologies for that. 9.4 was the c++ version. I have updated the relevant version of CMake and c++.

**Comment by hydai** [comment] 2023-06-14 17:50
Sure, all you need to do is:

1. Create a dockerfile from a base image (ubuntu:20.04)
2. Put the reproduce steps in the RUN command (You can find complex examples from the official docker website)
3. After installing all dependencies with dockerfile, it will make everyone on the same page.

**Comment by eshaanagarwal** [comment] 2023-06-14 18:36
> Sure, all you need to do is:
> 
> 1. Create a dockerfile from a base image (ubuntu:20.04)
> 2. Put the reproduce steps in the RUN command (You can find complex examples from the official docker website)
> 3. After installing all dependencies with dockerfile, it will make everyone on the same page.

Hi I have prepared the dockerfile for this. Should I share it here ? 
```
# Download base image ubuntu 20.04
FROM ubuntu:20.04

RUN git clone https://github.com/WasmEdge/WasmEdge.git && cd WasmEdge
RUN apt install -y software-properties-common cmake libboost-all-dev
RUN apt install -y llvm-12-dev liblld-12-dev
RUN apt install -y gcc g++

RUN export PYTORCH_VERSION="1.8.2"
RUN curl -s -L -O --remote-name-all https://download.pytorch.org/libtorch/lts/1.8/cpu/libtorch-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip
RUN unzip -q "libtorch-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip"
RUN rm -f "libtorch-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip"
RUN export LD_LIBRARY_PATH=$(pwd)/libtorch/lib:${LD_LIBRARY_PATH}
RUN export Torch_DIR=$(pwd)/libtorch
RUN mkdir -p build && cd build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="PyTorch" .. && make -j
RUN cmake --install .

RUN cd ../../

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
RUN rustup target add wasm32-wasi

```

Then you need to run these commands 
```bash
git clone https://github.com/second-state/WasmEdge-WASINN-examples.git
cd WasmEdge-WASINN-examples/pytorch-mobilenet-image
wasmedge --dir .:. wasmedge-wasinn-example-mobilenet-image.wasm mobilenet.pt input.jpg
```

**Comment by eshaanagarwal** [comment] 2023-06-17 20:37
@hydai any idea about this please ?

**Comment by hydai** [comment] 2023-06-17 20:44
https://wasmedge.org/docs/develop/build-and-run/install/#wasi-nn-plugin-with-pytorch-backend

```
export PYTORCH_VERSION="1.8.2"
# For the Ubuntu 20.04 or above, use the libtorch with cxx11 abi.
# export PYTORCH_ABI="libtorch-cxx11-abi"
# For the manylinux2014, please use the without cxx11 abi version:
export PYTORCH_ABI="libtorch"
curl -s -L -O --remote-name-all https://download.pytorch.org/libtorch/lts/1.8/cpu/${PYTORCH_ABI}-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip
unzip -q "${PYTORCH_ABI}-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip"
rm -f "${PYTORCH_ABI}-shared-with-deps-${PYTORCH_VERSION}%2Bcpu.zip"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(pwd)/libtorch/lib
```

You have to use `export PYTORCH_ABI="libtorch-cxx11-abi"` on Ubuntu20.04.

**Comment by eshaanagarwal** [comment] 2023-06-17 21:46
Ok this did work. I still think there are some discrepancies in building it from the source and other kinds of installation.
thank you so much

**Comment by alabulei1** [comment] 2023-06-19 04:28
Since it works. I will close this issue.

**Closed by alabulei1** 2023-06-19 04:28 UTC
