### ISSUE TITLE
question: https://wasmedge.org/docs/develop/deploy/podman/#prerequisites missing crun instructions

### ISSUE THREAD

**Issue by nareddyt** [WasmEdge/WasmEdge#3028] opened 2023-11-09 20:58 UTC
### Summary

Step 3 of https://wasmedge.org/docs/develop/deploy/podman/#prerequisites: It seems like some instructions are missing.

> Build and configure crun with WasmEdge support

> Next, configure and build a crun binary with WasmEdge support.

Maybe there should be a git clone, similar to https://wasmedge.org/docs/develop/deploy/oci-runtime/crun/#prerequisites?

**Comment by hydai** [comment] 2023-11-13 06:06
Hi @nareddyt 
Thanks for reporting this.

Yup, it looks like the `git clone` part is missed. @alabulei1 Should we move this issue to https://github.com/WasmEdge/docs ?

**Comment by hydai** [comment] 2023-11-23 16:50
The issue is moved to docs. Closing.

**Closed by hydai** 2023-11-23 16:50 UTC
Labels: documentation, question
