### ISSUE TITLE
[RISC-V] Build error when build AOT runtime with riscv-gnu-toolchain

### ISSUE THREAD

**Issue by O3Ol** [WasmEdge/WasmEdge#1694] opened 2022-07-28 10:06 UTC
By using the RISC-V cross-compilation toolchain to build the AOT mode of WasmEdge, the following error occurred. I found that `lib/aot/compiler.cpp` defines the  `x86_64` and `aarch64` architectures respectively, but does not describe the `RISC-V` architecture. Maybe this is the reason for the build error?

```
Scanning dependencies of target wasmedge
[ 96%] Building CXX object tools/wasmedge/CMakeFiles/wasmedge.dir/wasmedger.cpp.o
[ 97%] Linking CXX executable wasmedge
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeGetFunctionList[abi:cxx11]() const'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeValidate()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Driver::Tool(int, char const**)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Allocator::allocate(unsigned int)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `fmt::v8::detail::dragonbox::decimal_fp<float> fmt::v8::detail::dragonbox::to_decimal<float>(float)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `int fmt::v8::detail::snprintf_float<double>(double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeLoadWasm(std::filesystem::__cxx11::path const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Loader::Loader::parseModule(cxx20::span<unsigned char const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `fmt::v8::detail::dragonbox::decimal_fp<double> fmt::v8::detail::dragonbox::to_decimal<double>(double)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::This'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::ErrInfo::operator<<(std::ostream&, WasmEdge::ErrInfo::InfoMismatch const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeInstantiate()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::asyncExecute(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::convertUIntToHexStr[abi:cxx11](unsigned long, unsigned int)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Allocator::release(unsigned char*, unsigned int)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeExecute(std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `char fmt::v8::detail::decimal_point_impl<char>(fmt::v8::detail::locale_ref)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Plugin::Plugin::load(std::filesystem::__cxx11::path const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRunWasmFile(cxx20::span<unsigned char const, 18446744073709551615ul>, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::ErrInfo::operator<<(std::ostream&, WasmEdge::ErrInfo::InfoBoundary const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::asyncRunWasmFile(WasmEdge::AST::Module const&, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::asyncRunWasmFile(cxx20::span<unsigned char const, 18446744073709551615ul>, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Allocator::resize(unsigned char*, unsigned int, unsigned int)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRegisterModule(WasmEdge::Runtime::Instance::ModuleInstance const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRegisterModule(std::basic_string_view<char, std::char_traits<char> >, std::filesystem::__cxx11::path const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `fmt::v8::format_error::~format_error()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeExecute(std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `typeinfo for fmt::v8::format_error'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Host::WasiModule::WasiModule()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Log::setErrorLoggingLevel()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Validator::Validator::validate(WasmEdge::AST::Module const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::atomicNotifyAll()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `spdlog::details::backtracer::enabled() const'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::asyncRunWasmFile(std::filesystem::__cxx11::path const&, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `int fmt::v8::detail::format_float<long double>(long double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::MMap::~MMap()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `spdlog::details::log_msg::log_msg(spdlog::source_loc, fmt::v8::basic_string_view<char>, spdlog::level::level_enum, fmt::v8::basic_string_view<char>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::VM(WasmEdge::Configure const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeGetActiveModule() const'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRunWasmFile(std::filesystem::__cxx11::path const&, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeGetImportModule(WasmEdge::HostRegistration) const'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `int fmt::v8::detail::format_float<double>(double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::AOT::Compiler::compile(cxx20::span<unsigned char const, 18446744073709551615ul>, WasmEdge::AST::Module const&, std::filesystem::__cxx11::path)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::registerModule(WasmEdge::Runtime::StoreManager&, WasmEdge::AST::Module const&, std::basic_string_view<char, std::char_traits<char> >)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::invoke(WasmEdge::Runtime::Instance::FunctionInstance const&, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeLoadWasm(cxx20::span<unsigned char const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `spdlog::default_logger_raw()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRegisterModule(std::basic_string_view<char, std::char_traits<char> >, cxx20::span<unsigned char const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `int fmt::v8::detail::snprintf_float<long double>(long double, int, fmt::v8::detail::float_specs, fmt::v8::detail::buffer<char>&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRegisterModule(std::basic_string_view<char, std::char_traits<char> >, WasmEdge::AST::Module const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeCleanup()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::instantiateModule(WasmEdge::Runtime::StoreManager&, WasmEdge::AST::Module const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `fmt::v8::detail::thousands_sep_result<char> fmt::v8::detail::thousands_sep_impl<char>(fmt::v8::detail::locale_ref)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Plugin::Plugin::findModule(std::basic_string_view<char, std::char_traits<char> >) const'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `std::locale fmt::v8::detail::locale_ref::get<std::locale>() const'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Plugin::Plugin::find(std::basic_string_view<char, std::char_traits<char> >)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeLoadWasm(WasmEdge::AST::Module const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Host::WASI::Environ::init(cxx20::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cxx20::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>, cxx20::span<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::ExecutionContext'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Driver::Compiler(int, char const**)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::unsafeRunWasmFile(WasmEdge::AST::Module const&, std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Plugin::Plugin::getDefaultPluginPaths[abi:cxx11]()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `fmt::v8::detail::error_handler::on_error(char const*)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Loader::Loader::parseModule(std::filesystem::__cxx11::path const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `vtable for fmt::v8::format_error'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Log::setDebugLoggingLevel()'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::asyncExecute(std::basic_string_view<char, std::char_traits<char> >, cxx20::span<WasmEdge::Variant<unsigned int, int, unsigned long, long, float, double, unsigned __int128, __int128, unsigned long __vector(2), long __vector(2), unsigned int __vector(4), int __vector(4), unsigned short __vector(8), short __vector(8), unsigned char __vector(16), signed char __vector(16), float __vector(4), double __vector(2), WasmEdge::UnknownRef, WasmEdge::FuncRef, WasmEdge::ExternRef> const, 18446744073709551615ul>, cxx20::span<WasmEdge::ValType const, 18446744073709551615ul>)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Loader::Loader::loadFile(std::filesystem::__cxx11::path const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::Executor::Executor::registerModule(WasmEdge::Runtime::StoreManager&, WasmEdge::Runtime::Instance::ModuleInstance const&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `WasmEdge::VM::VM::VM(WasmEdge::Configure const&, WasmEdge::Runtime::StoreManager&)'
/opt/riscv64/lib/gcc/riscv64-unknown-linux-gnu/11.1.0/../../../../riscv64-unknown-linux-gnu/bin/ld: ../../lib/api/libwasmedge_c.so: undefined reference to `spdlog::logger::log_it_(spdlog::details::log_msg const&, bool, bool)'
collect2: error: ld returned 1 exit status
make[2]: *** [tools/wasmedge/CMakeFiles/wasmedge.dir/build.make:104：tools/wasmedge/wasmedge] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1177：tools/wasmedge/CMakeFiles/wasmedge.dir/all] 错误 2
make: *** [Makefile:171：all] 错误 2
```

**Comment by hydai** [comment] 2022-07-28 14:25
The linker reports these errors. If the `RISC-V` is not defined, it will report errors earlier.
Could you please provide the reproduced steps? It seems like it cannot find the `libwasmedge`, `spdlog`, and `fmt` in the linking time.

**Comment by O3Ol** [comment] 2022-07-28 15:43
> 

 Σ( °△°|||)︴OK...I found that `-DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY` was set in my compile items, which caused the problem. So the problem is solved by removing the item.

**Comment by hydai** [comment] 2022-07-29 07:24
Seems like the issue is resolved. I am closing this, if there is any new problem, please create a new one.

**Closed by hydai** 2022-07-29 07:24 UTC
