### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by sz8881** [WasmEdge/WasmEdge#3562] opened 2024-07-14 09:45 UTC
### Summary

 * Failed to install WasmEdge

### Current State

 * Failed to install WasmEdge

### Expected State

 * Failed to install WasmEdge

### Reproduction steps

1. Build with options '...'
2. Execute with flags '....'
3. Execute with inputs '....'
4. Get error

### Screenshots

![DESCRIPTION](LINK.png)

### Any logs you want to share for showing the specific issue

 * Failed to install WasmEdge

### Components

CLI

### WasmEdge Version or Commit you used

1

### Operating system information

macos14.1

### Hardware Architecture

x86

### Compiler flags and options

 * Failed to install WasmEdge

**Comment by hydai** [comment] 2024-07-14 10:51
Closing it due to no detailed logs, no screenshots, and no way to reproduce it.

**Closed by hydai** 2024-07-14 10:51 UTC
Labels: bug
