### ISSUE TITLE
Building of WasmEdge with WASI-NN PyTorch Backend failed

### ISSUE THREAD

**Issue by eshaanagarwal** [WasmEdge/WasmEdge#2499] opened 2023-05-15 10:25 UTC
## Description
I was setting up my development environment. Particularly WASI-NN PyTorch Backend. 
I followed all the steps on the guide and documentation but got this weird error.
### Current State
```
-- Downloading the WASM spec test suite
-- Downloading the WASM spec test suite -- done
-- RapidJSON found. Headers: /home/eshaan/Desktop/cncf/WasmEdge/build/_deps/rapidjson-src/include
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/core
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/core -- done
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/multi-memory
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/multi-memory -- done
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/tail-call
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/tail-call -- done
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/extended-const
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/extended-const -- done
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/threads
-- Copying test suite to /home/eshaan/Desktop/cncf/WasmEdge/build/test/spec/testSuites/threads -- done
-- Download ML artifacts to /home/eshaan/Desktop/cncf/WasmEdge/build/test/plugins/wasi_nn/wasinn_pytorch_fixtures
CMake Error at test/plugins/wasi_nn/CMakeLists.txt:35 (file):
  file MD5 failed to read file
  "/home/eshaan/Desktop/cncf/WasmEdge/build/test/plugins/wasi_nn/wasinn_pytorch_fixtures/mobilenet.pt":
  No such file or directory


CMake Error at test/plugins/wasi_nn/CMakeLists.txt:36 (file):
  file MD5 failed to read file
  "/home/eshaan/Desktop/cncf/WasmEdge/build/test/plugins/wasi_nn/wasinn_pytorch_fixtures/image-1x3x224x224.rgb":
  No such file or directory


CMake Error at test/plugins/wasi_nn/CMakeLists.txt:38 (message):
  mobilenet.pt downloaded with wrong md5


-- Configuring incomplete, errors occurred!
See also "/home/eshaan/Desktop/cncf/WasmEdge/build/CMakeFiles/CMakeOutput.log".
See also "/home/eshaan/Desktop/cncf/WasmEdge/build/CMakeFiles/CMakeError.log".
```

## Environment

- Hardware Architecture: (e.g. x86\_64 )
- Operating system: (e.g. Ubuntu 20.04 )

## Steps to Reproduce

Build Wasmedge from source in Linux 20.04
commands used -
```
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="PyTorch" .. && make -j
# For the WASI-NN plugin, you should install this project.
cmake --install .
```

**Comment by q82419** [comment] 2023-05-17 11:49
I'll take a look in these days. Thanks.

**Comment by q82419** [comment] 2023-05-18 19:54
Hi @eshaanagarwal ,

I cannot reproduce this issue.
Please check that you download the test data successfully.
Refer to the script: `utils/wasi-nn/download-pytorch-fixtures.sh`
Thanks.

**Comment by eshaanagarwal** [comment] 2023-06-10 11:42
Hi sorry for the late response. But I am still stuck with this issue. I have tried to also do a fresh build. can you please tell me what you mean by your last comment.

**Comment by hydai** [comment] 2023-06-10 11:49
> Hi sorry for the late response. But I am still stuck with this issue. I have tried to also do a fresh build. can you please tell me what you mean by your last comment.

Those not found files are downloaded by `utils/wasi-nn/download-pytorch-fixtures.sh`. You can try to run this script manually to check if there is a network issue.

**Comment by eshaanagarwal** [comment] 2023-06-10 12:09
Ok so i tried to run that script. It is working but now I am getting a different error.
```bash
CMake Error at cmake/WASINNDeps.cmake:16 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  test/plugins/wasi_nn/CMakeLists.txt:66 (include)


-- Configuring incomplete, errors occurred!
See also "/home/eshaan/Desktop/cncf/WasmEdge/build/CMakeFiles/CMakeOutput.log".
See also "/home/eshaan/Desktop/cncf/WasmEdge/build/CMakeFiles/CMakeError.log".
```

**Comment by juntao** [comment] 2023-06-10 12:20
Which guide / documentation did you follow? Thanks.

**Comment by eshaanagarwal** [comment] 2023-06-10 12:29
Hi ! So i am referring to this link : https://wasmedge.org/book/en/contribute/build_from_src/plugin_wasi_nn.html

**Comment by q82419** [comment] 2023-06-11 22:39
You should follow the [torch part of this guide](https://wasmedge.org/book/en/contribute/build_from_src/plugin_wasi_nn.html#build-wasmedge-with-wasi-nn-pytorch-backend) to install the torch dependency and set the environment variable first.
The cmake will then find the torch library.
Thanks.

**Comment by eshaanagarwal** [comment] 2023-06-12 12:35
> You should follow the [torch part of this guide](https://wasmedge.org/book/en/contribute/build_from_src/plugin_wasi_nn.html#build-wasmedge-with-wasi-nn-pytorch-backend) to install the torch dependency and set the environment variable first. The cmake will then find the torch library. Thanks.
Hi ! I have followed all the guide now. And pasted the commands in terminal at this directory for it to work
```bash
eshaan@eshaan:~/Desktop/cncf/WasmEdge$
```
As part of following all the commands, everything was fine till 
```
cmake -DCMAKE_BUILD_TYPE=Release -DWASMEDGE_PLUGIN_WASI_NN_BACKEND="PyTorch" .. && make -j
```
but then i got this error which i resolved like this :

```bash
eshaan@eshaan:~/Desktop/cncf/WasmEdge/build$ cmake --install .
-- Install configuration: "Release"
-- Installing: /usr/local/lib/libwasmedge.so.0.0.2
CMake Error at lib/api/cmake_install.cmake:57 (file):
  file INSTALL cannot copy file
  "/home/eshaan/Desktop/cncf/WasmEdge/build/lib/api/libwasmedge.so.0.0.2" to
  "/usr/local/lib/libwasmedge.so.0.0.2": Permission denied.
Call Stack (most recent call first):
  lib/cmake_install.cmake:102 (include)
  cmake_install.cmake:52 (include)


eshaan@eshaan:~/Desktop/cncf/WasmEdge/build$ sudo cmake --install .
- Install configuration: "Release"
-- Installing: /usr/local/lib/libwasmedge.so.0.0.2
-- Up-to-date: /usr/local/lib/libwasmedge.so.0
-- Set runtime path of "/usr/local/lib/libwasmedge.so.0.0.2" to ""
-- Up-to-date: /usr/local/lib/libwasmedge.so
-- Up-to-date: /usr/local/include/wasmedge/wasmedge.h
-- Installing: /usr/local/include/wasmedge/version.h
-- Installing: /usr/local/include/wasmedge/enum.inc
-- Installing: /usr/local/include/wasmedge/enum_configure.h
-- Installing: /usr/local/include/wasmedge/enum_errcode.h
-- Installing: /usr/local/include/wasmedge/enum_types.h
-- Up-to-date: /usr/local/include/wasmedge/int128.h
-- Installing: /usr/local/lib/wasmedge/libwasmedgePluginWasiNN.so
-- Set runtime path of "/usr/local/lib/wasmedge/libwasmedgePluginWasiNN.so" to ""
-- Installing: /usr/local/bin/wasmedgec
-- Set runtime path of "/usr/local/bin/wasmedgec" to "$ORIGIN/../lib"
-- Installing: /usr/local/bin/wasmedge
-- Set runtime path of "/usr/local/bin/wasmedge" to "$ORIGIN/../lib"
```
Now when i try to run one of the examples of AI inference from - https://wasmedge.org/docs/develop/rust/ai_inference/pytorch/
I got the following error : 
```bash
eshaan@eshaan:~/Desktop/cncf/WasmEdge-WASINN-examples$ wasmedge --dir .:. wasmedge-wasinn-example-mobilenet-image.wasm mobilenet.pt input.jpg
[2023-06-12 17:53:35.718] [error] loading failed: invalid path, Code: 0x20
[2023-06-12 17:53:35.718] [error]     File name: "/home/eshaan/Desktop/cncf/WasmEdge-WASINN-examples/wasmedge-wasinn-example-mobilenet-image.wasm"
```

I don't not quite understand where I am wrong

**Comment by hydai** [comment] 2023-06-12 17:11
Hi @eshaanagarwal 
I think the file is located in `pytorch-mobilenet-image` folder. So there is a mistake in the document.
@alabulei1 Where should I raise the issue about the wrong document?

**Comment by hydai** [comment] 2023-06-12 17:37
Please open another issue. I didn't encounter this before, so I will need detailed information on your environment including OS, toolchain, and any related hints.

**Comment by font** [comment] 2023-06-13 23:41
@eshaanagarwal I also ran into the undefined symbol lookup error at first: `/home/ifont/src/wasmedge/wasmedge/build/tools/wasmedge/wasmedge: symbol lookup error: /home/ifont/src/wasmedge/wasmedge/build/plugins/wasi_nn/libwasmedgePluginWasiNN.so: undefined symbol: _ZNK5torch3jit6Object11find_methodERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
`.

Make sure you reset environment variables, have a working download of the PyTorch libraries `1.8.2`, perform a clean fresh build of `wasmedge` `0.12.1` along with an updated clone of the https://github.com/second-state/WasmEdge-WASINN-examples repo.

**Comment by eshaanagarwal** [comment] 2023-06-14 17:06
> @eshaanagarwal I also ran into the undefined symbol lookup error at first: `/home/ifont/src/wasmedge/wasmedge/build/tools/wasmedge/wasmedge: symbol lookup error: /home/ifont/src/wasmedge/wasmedge/build/plugins/wasi_nn/libwasmedgePluginWasiNN.so: undefined symbol: _ZNK5torch3jit6Object11find_methodERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE `.
> 
> Make sure you reset environment variables, have a working download of the PyTorch libraries `1.8.2`, perform a clean fresh build of `wasmedge` `0.12.1` along with an updated clone of the https://github.com/second-state/WasmEdge-WASINN-examples repo.

i did a clean build and still face the same issue. I will make a separate issue for this I guess.

**Comment by eshaanagarwal** [comment] 2023-06-14 17:37
> Hi @eshaanagarwal I think the file is located in `pytorch-mobilenet-image` folder. So there is a mistake in the document. @alabulei1 Where should I raise the issue about the wrong document?

Also I would be up to quickly fix this in wasmedge documentation. if it seems right to you guys.

**Comment by hydai** [comment] 2023-06-14 17:38
> > Hi @eshaanagarwal I think the file is located in `pytorch-mobilenet-image` folder. So there is a mistake in the document. @alabulei1 Where should I raise the issue about the wrong document?
> 
> Also I would be up to quickly fix this in wasmedge documentation. if it seems right to you guys.

Sure. Please raise a PR on the new docs repo. Thanks :-)

**Comment by hydai** [comment] 2024-06-06 23:12
The issue is resolved, closing it.

**Closed by hydai** 2024-06-06 23:12 UTC
